name: Build Go Program (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -o myprogram.exe

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: myprogram
        path: ./myprogram.exe
